phone/urls.py
from django.urls import path
from . import views

app_name = 'phone'

urlpatterns = [
    # phone urls for crud operations
    path('phone/', views.PhoneList.as_view(), name='phone_list'),
    path('phone/add/', views.PhoneCreate.as_view(), name='phone_add'),
    path('phone/<int:pk>/detail/', views.PhoneDetail.as_view(), name='phone_detail'),
    path('phone/<int:pk>/update/', views.PhoneUpdate.as_view(), name='phone_update'),
    path('phone/<int:pk>/delete/', views.PhoneDelete.as_view(), name='phone_delete'),

    # datatable url
    path('phone/datatable/', views.PhoneDatatable.as_view(), name='phone_datatable'),
]

phonenumbers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('phone/', include('phone.urls')),
]

phone/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

class Phone(models.Model):
    office = models.CharField(max_length=200)
    abbreviation = models.CharField(max_length=200)
    number = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='phone_phone')

    def get_absolute_url(self):
        return reverse('phone:phone_detail', kwargs={'pk': self.pk})

phone/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.template.loader import render_to_string
# messages framework
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
# class-based generic views
from django.views.generic import TemplateView, ListView, DetailView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
# import models
from django.contrib.auth.models import User
from .models import Phone

class PhoneDatatable(TemplateView): 
    template_name = 'phone/phone/phone_datatable.html'

class PhoneList(ListView): 
    model = Phone
    template_name = 'phone/phone/phone_list.html'
    context_object_name = 'phone_list'
    paginate_by = 5


class PhoneDetail(DetailView): 
    model = Phone
    template_name = 'phone/phone/phone_detail.html'
    context_object_name = 'phone'


class PhoneCreate(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, CreateView): # create phone 
    model = Phone
    initial = {'office': 'office name', 'abbreviation': 'abrv', 'number': '123456'}
    template_name = 'phone/phone/phone_form_create.html' 
    fields = ['office', 'abbreviation', 'number']
    success_message = "phone was created successfully"
    permission_required = 'phone.add_phone'

    def form_valid(self, form):
        form.instance.created_by = self.request.user 
        return super().form_valid(form)


class PhoneUpdate(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, UpdateView): # update phone 
    model = Phone
    template_name = 'phone/phone/phone_form_update.html' 
    fields = ['office', 'abbreviation', 'number']
    success_message = "phone was updated successfully"
    permission_required = 'phone.change_phone'

    def form_valid(self, form):
        if form.instance.created_by == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponse("you don't have permissions")

# delete phone 
class PhoneDelete(SuccessMessageMixin, PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Phone
    template_name = 'phone/phone/phone_confirm_delete.html' 
    success_message = "phone was deleted successfully"
    success_url = reverse_lazy('phone:phone_list')
    permission_required = 'phone.delete_phone'

    def form_valid(self, form):
        if form.instance.created_by == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponse("you don't have permissions")

phone/templates/phone/phone/pagination.html
<br>
<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <span class="page-link">
                            {{ i }}
                            <span class="sr-only">(current)</span>
                        </span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>

phone/templates/phone/phone/phone_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>


{% endblock %}

phone/templates/phone/phone/phone_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2>{{ phone.office }}</h2>
<p>{{ phone.abbreviation }}</p>
<p>{{ phone.number }}</p>
<br>
<!-- Display 'Edit' and 'Delete' buttons -->
{% if user.is_authenticated and phone.created_by == user %}
<p>
<a href="{% url 'phone:phone_update' phone.pk %}" class="btn btn-primary"> Update </a> 
<a href="{% url 'phone:phone_delete' phone.pk %}" class="btn btn-danger"> Delete </a>
</p>
<hr />
{% endif %}

<hr />

{% endblock %}

phone/templates/phone/phone/phone_form_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

 
<h3>Create phone</h3>

<form action="{% url 'phone:phone_add' %}" method="post" novalidate enctype="multipart/form-data" class="uniForm">
    {{ form|crispy }}
    {% csrf_token %}
    <br>
    <p><input type="submit" value="Create" class='btn btn-primary'></p>
</form>



{% endblock %}

phone/templates/phone/phone/phone_form_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h3>Update phone </h3>

<form action="{% url 'phone:phone_update' phone.id %}" method="post" novalidate enctype="multipart/form-data" class="uniForm">
    {{ form|crispy }}
    {% csrf_token %}
    <p><input type="submit" value="Update" class='btn btn-primary'></p>
</form>

{% endblock %}

phone/templates/phone/phone/phone_list.html
{% extends 'base.html' %}

{% block content %}

<!-- Display list of all phones -->
{% for phone in phone_list %}
<div class="card bg-light mb-3" style="max-width: 100%;">
  <div class="card-header">{{ phone.abbreviation }} - {{ phone.number }}</div>
  <div class="card-body">
    <a href="{{ phone.get_absolute_url }}">Detail</a>
  </div>
</div>
{% empty %}
<p>No phone Yet</p>
{% endfor %}


<!-- Display pagination only if page_obj have some value -->
{% if page_obj %}
  {% include "phone/phone/pagination.html" with page=page_obj %}
{% endif %}


{% endblock %}